version: '3.8'
services:
  display:
    hostname: display
    build: src
    #image: docker.pkg.github.com/kipjr/docker-display/docker-display-image:latest
    container_name: display
    ipc: host # level=error msg="add cg to OOM monitor" error="cgroups: memory cgroup not supported on this system"
    devices:
       - "/dev/dri/card0:/dev/dri/card0"
       - "/dev/dri/card1:/dev/dri/card1"
       - "/dev/fb0:/dev/fb0"
      # - "/dev/input/event0:/dev/input/event0" #toucscreen
      # - "/dev/input/mice:/dev/input/mice" #mouse (multi / hotplug)
      # - "/dev/input/mouse0:/dev/input/mouse0" #mouse
       - "/dev/input/:/dev/input/"
       - "/dev/tty0:/dev/tty0"
       - "/dev/tty1:/dev/tty1"
       - "/dev/tty2:/dev/tty2"
       - "/dev/tty3:/dev/tty3"
       - "/dev/tty4:/dev/tty4"
       - "/dev/tty5:/dev/tty5"
       - "/dev/tty6:/dev/tty6"
       - "/dev/tty7:/dev/tty7"
       - "/dev/tty8:/dev/tty8"
       - "/dev/tty9:/dev/tty9"
    environment:
       - 'TZ=Europe/Amsterdam'
       - DISPLAY=:0
       - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
       - MQTT_HOST=192.168.1.4
       - MQTT_PORT=1433
       - MQTT_TOPIC=scripts/display/power
       - URL=http://home-assistant:8123
       - WIDTH=1366
       - HEIGHT=800
       - CHROMIUMFLAGS='--window-position=0,0 --start-fullscreen --kiosk --incognito --noerrdialogs --disable-translate --no-first-run --fast --fast-start --disable-infobars --disable-features=TranslateUI --disk-cache-dir=/tmp/chromium --overscroll-history-navigation=0 --disable-pinch'
    volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix #display
       - /var/run/dbus:/var/run/dbus #needed for something
       - /run/udev/data:/run/udev/data #needed for input
       - ./logs:/var/log
    cap_add:
      - "cap_sys_admin" #needed for modeset(0): drmSetMaster failed: Permission denied
    #restart: unless-stopped
    privileged: false
    networks:
      - net
      - intranet

#Docker Networks
networks:
  intranet:
    external:
      name: intranet
  net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.8.24/29 #192.168.8.25 - 192.168.8.30 (bc:31)
    driver_opts:
     com.docker.network.bridge.name: display_net

