version: '3.8'
services:

  #Display
  #
  #  
  # Touchscreen: WS170120 sudo ./LCD7-1024x600-show
  # max_usb_current=1
  # hdmi_group=2
  # hdmi_mode=87
  # hdmi_cvt 1024 600 60 6 0 0 0
  #
  # Sources
  # 
  # https://sylvaindurand.org/launch-chromium-in-kiosk-mode/#:~:text=Chromium%20makes%20it%20easy%20to,display%20or%20on%20a%20terminal%E2%80%A6
  # https://www.waveshare.com/wiki/7inch_HDMI_LCD_(H)_(with_case)
  # https://www.waveshare.com/wiki/5inch_HDMI_LCD_(B)_(Firmware_Rev_2.1)_User_Manual
  # https://stackoverflow.com/questions/33585482/keyboard-mouse-are-unresponsable-when-running-x-org-in-a-docker-container
  # https://wiki.ubuntu.com/X/InputCoordinateTransformation
  # https://help.ubuntu.com/community/TabletSetup
  # https://jonathanmh.com/raspberry-pi-4-kiosk-wall-display-dashboard/
  # https://forums.balena.io/t/cant-get-chromium-browser-working/142217
  # https://forums.balena.io/t/create-a-non-root-user-on-x11-window-manager/63131
  # https://github.com/balena-io-examples/x11-window-manager/blob/master/Dockerfile.raspberrypi3
  # https://www.balena.io/blog/running-a-desktop-manager-with-balena/
  # http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/
  # https://askubuntu.com/questions/1161646/is-it-possible-to-run-docker-container-and-show-its-graphical-application-window
  # https://hub.docker.com/r/thomaskatalis/rpi-kiosk/dockerfile
  # https://github.com/waveshare/LCD-show
  # 
  # bpfcc-tools libcap-ng-utils  /usr/share/bcc/tools/capable & pscap
  #
  display:
    hostname: display
    build: .
    container_name: display
    ipc: host # level=error msg="add cg to OOM monitor" error="cgroups: memory cgroup not supported on this system"
    devices:
       - "/dev/dri/card0:/dev/dri/card0"
       - "/dev/dri/card1:/dev/dri/card1"
       - "/dev/fb0:/dev/fb0"
      # - "/dev/input/event0:/dev/input/event0" #toucscreen
      # - "/dev/input/mice:/dev/input/mice" #mouse (multi / hotplug)
      # - "/dev/input/mouse0:/dev/input/mouse0" #mouse
       - "/dev/input/:/dev/input/"
       - "/dev/tty0:/dev/tty0"
       - "/dev/tty1:/dev/tty1"
       - "/dev/tty2:/dev/tty2"
    environment:
       - DISPLAY=:0
       - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix #display
       - /lib/modules:/lib/modules
       - /var/run/dbus:/var/run/dbus
       - /run/udev/data:/run/udev/data
    cap_add:
      - "cap_sys_admin"
      - "sys_tty_config"
      - "cap_sys_module"
      - "cap_sys_rawio"
    cap-drop:
      - "SYS_TIME"
    restart: unless-stopped
    privileged: true
    networks:
      - net

#Docker Networks
networks:
  net:
    driver: bridge




# version: '3.8'
# services:

#   #Display
#   display:
#     hostname: display
#     build: .
#     container_name: display
#     ipc: host
#     devices:
#        - "/dev/tty0:/dev/tty0"
#     environment:
#        - DISPLAY=localhost:0
#        - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
#     volumes:
#        - /tmp/.X11-unix:/tmp/.X11-unix
#        - /lib/modules:/lib/modules
#        - /run/dbus:/host/run/dbus
#        #- /host/run/dbus/system_bus_socket:/host/run/dbus/system_bus_socket
#     restart: unless-stopped
#     privileged: true
#     networks:
#       - net

# #Docker Networks
# networks:
#   net:
#     driver: bridge
    