#Docker Networks
networks:
  intranet:
    external:
      name: intranet
  net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.8.9/29 #192.168.8.10 - 192.168.8.14 (bc:15)
    driver_opts:
     com.docker.network.bridge.name: display_net

volumes:
  chromium-data:

services:
  display:
    hostname: display
    image: ghcr.io/kipjr/docker-display:debian-bookworm-firefox-esr
    build:
      context: src
      args:
        BROWSER: ${BROWSER:-firefox-esr}
        OS_VERSION: ${OS_VERSION:-debian:bookworm}
    platform: "linux/arm64/v8"
    container_name: display
    ipc: host # level=error msg="add cg to OOM monitor" error="cgroups: memory cgroup not supported on this system"
    devices:
       - "/dev/dri/card0:/dev/dri/card0"
       - "/dev/dri/card1:/dev/dri/card1"
       - "/dev/fb0:/dev/fb0"
      # - "/dev/input/event0:/dev/input/event0" #toucscreen
      # - "/dev/input/mice:/dev/input/mice" #mouse (multi / hotplug)
      # - "/dev/input/mouse0:/dev/input/mouse0" #mouse
       - "/dev/input/:/dev/input/"
       - "/dev/tty0:/dev/tty0"
       - "/dev/tty1:/dev/tty1"
       - "/dev/tty2:/dev/tty2"
       - "/dev/tty3:/dev/tty3"
       - "/dev/tty4:/dev/tty4"
       - "/dev/tty5:/dev/tty5"
       - "/dev/tty6:/dev/tty6"
       - "/dev/tty7:/dev/tty7"
       - "/dev/tty8:/dev/tty8"
       - "/dev/tty9:/dev/tty9"
    environment:
       - 'TZ=Europe/Amsterdam'
       - DISPLAY=:0
       - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
       - MQTT_HOST=192.168.1.4
       - MQTT_PORT=1433
       - MQTT_TOPIC=sensor/display/power
       - URL=http://home-assistant:8123
       - WIDTH=1366
       - HEIGHT=800
       - CHROMIUMFLAGS=--start-fullscreen --kiosk --noerrdialogs --disable-translate --no-first-run --fast --fast-start --disable-infobars --disable-features=TranslateUI --disable-cache --disk-cache-dir=/dev/null --disk-cache-size=1 --overscroll-history-navigation=0 --disable-pinch --disable-overlay-scrollbar
    volumes:
       - /var/run/dbus:/var/run/dbus #needed for something
       - /run/udev/data:/run/udev/data #needed for input
       - chromium-data:/home/display/.config/chromium
       - firefox-data:/home/display/.mozilla
    cap_add:
      - "cap_sys_admin" #needed for modeset(0): drmSetMaster failed: Permission denied
    privileged: false
    restart: unless-stopped
    networks:
      - net
      - intranet

