---
name: Lint

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
  pull_request:

permissions: {}
 
jobs:
  lint-check:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run Super-linter
      - name: Super-linter
        uses: super-linter/super-linter/slim@v7.2.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #VALIDATE_BASH_EXEC: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          #VALIDATE_SHELL_SHFMT: true
          VALIDATE_YAML_PRETTIER: true
